import fs from "node:fs";
import path from "node:path";

export const REC_SCHEMA_VERSION = "2026-08-23";
export const REC_SCHEMA_MARKDOWN_PATH = "docs/conference-schema.md";

export const REC_SCHEMA = {
  activeConference: {
    title: "Renewable Energy Conference & Expo 2026",
    shortName: "REC26 & EXPO",
    activeRowId: "6863b66b0016bd6d77ff",
    defaultFilter: "REC_Conferences.isActive = true",
    historicalRule:
      "Use an explicit year, REC edition, or past/previous/history wording before selecting an inactive conference.",
  },
  tables: {
    conferences: {
      label: "REC_Conferences",
      purpose: "Conference-edition facts, dates, venue, registration status, theme, limits, contact, and website. Defaults to the active row.",
      fields: [
        "year",
        "title",
        "description",
        "startDate",
        "endDate",
        "location",
        "venue",
        "isActive",
        "registrationOpen",
        "maxAttendees",
        "registrationFee",
        "days",
        "maxExhibitors",
        "maxSponsors",
        "maxLimits",
        "currentCounts",
        "sponsorshipPackageUrl",
        "theme",
        "shortName",
        "fullName",
        "mainWebsiteUrl",
        "heroTagline",
        "contactEmail",
        "contactPhone",
        "regClosedMessage",
        "successMessage",
        "couponRequired",
      ],
      defaultFields: [
        "title",
        "shortName",
        "year",
        "theme",
        "startDate",
        "endDate",
        "venue",
        "location",
        "registrationOpen",
        "regClosedMessage",
        "mainWebsiteUrl",
      ],
      searchableFields: [
        "title",
        "shortName",
        "fullName",
        "description",
        "theme",
        "venue",
        "location",
        "heroTagline",
      ],
    },
    programs: {
      label: "REC_Program",
      purpose: "Programme containers for active and previous conference editions.",
      fields: [
        "conferenceId",
        "description",
        "daysCount",
        "venueHalls",
        "status",
        "slug",
        "title",
        "createdAt",
        "updatedAt",
      ],
      defaultFields: ["title", "description", "daysCount", "venueHalls", "status"],
      searchableFields: ["title", "description", "venueHalls", "status"],
    },
    timeBlocks: {
      label: "REC_ProgramTimeBlocks",
      purpose: "Scheduled blocks such as sessions, exhibition blocks, tea breaks, and lunch.",
      fields: [
        "conferenceId",
        "programId",
        "day",
        "date",
        "startTime",
        "endTime",
        "startMinutes",
        "endMinutes",
        "type",
        "label",
        "allowSessions",
        "venueScope",
        "venueHalls",
        "sortOrder",
        "notes",
      ],
      defaultFields: [
        "label",
        "day",
        "date",
        "startTime",
        "endTime",
        "type",
        "venueHalls",
        "notes",
      ],
      searchableFields: ["label", "type", "venueHalls", "notes", "date"],
    },
    sessions: {
      label: "REC_Sessions",
      purpose: "Published programme sessions.",
      fields: [
        "programId",
        "day",
        "startTime",
        "toTime",
        "venueHall",
        "theme",
        "title",
        "preamble",
        "organizer",
        "speakers",
        "status",
        "timeBlockIds",
        "sessionSpanType",
      ],
      defaultFields: [
        "title",
        "day",
        "startTime",
        "toTime",
        "venueHall",
        "theme",
        "preamble",
        "organizer",
        "speakers",
        "status",
      ],
      searchableFields: [
        "title",
        "theme",
        "preamble",
        "organizer",
        "speakers",
        "venueHall",
        "status",
      ],
    },
    sponsorCategories: {
      label: "REC_SponsorCategories",
      purpose: "Public sponsor and partner groupings.",
      fields: [
        "conferenceId",
        "name",
        "slug",
        "description",
        "accentColor",
        "displayOrder",
        "isActive",
      ],
      defaultFields: ["name", "slug", "description", "displayOrder", "isActive"],
      searchableFields: ["name", "slug", "description"],
    },
    sponsors: {
      label: "REC_Sponsors",
      purpose: "Public sponsors and partners.",
      fields: [
        "conferenceId",
        "categoryId",
        "name",
        "description",
        "siteUrl",
        "logoUrl",
        "displayOrder",
        "isActive",
        "isFeatured",
      ],
      defaultFields: [
        "name",
        "categoryId",
        "description",
        "siteUrl",
        "displayOrder",
        "isActive",
        "isFeatured",
      ],
      searchableFields: ["name", "description", "siteUrl"],
    },
    mediaItems: {
      label: "REC Media Items",
      purpose: "Published photo albums, videos, thumbnails, and sample conference images by conference edition.",
      fields: [
        "conferenceId",
        "conferenceYear",
        "mediaType",
        "title",
        "slug",
        "description",
        "externalUrl",
        "videoUrl",
        "thumbnailUrl",
        "thumbnailFileId",
        "sampleImagesJson",
        "displayOrder",
        "isFeatured",
        "isPublished",
        "updatedAt",
      ],
      defaultFields: [
        "conferenceYear",
        "mediaType",
        "title",
        "description",
        "externalUrl",
        "videoUrl",
        "sampleImagesJson",
      ],
      searchableFields: [
        "title",
        "description",
        "mediaType",
        "slug",
      ],
    },
    reports: {
      label: "REC Conference Reports",
      purpose:
        "Published conference reports, proceedings, outcomes, communiques, summaries, PDF links, and cover images by conference edition.",
      fields: [
        "conferenceId",
        "conferenceYear",
        "reportType",
        "title",
        "summary",
        "reportUrl",
        "coverImageUrl",
        "publicationDate",
        "displayOrder",
        "isFeatured",
        "isPublished",
        "updatedAt",
      ],
      defaultFields: [
        "conferenceYear",
        "reportType",
        "title",
        "summary",
        "reportUrl",
        "publicationDate",
        "isFeatured",
      ],
      searchableFields: ["title", "summary", "reportType"],
    },
    operationalInfo: {
      label: "Admin Published Operational Information",
      purpose: "Admin-managed public venue and visitor facts for the active conference, such as guest Wi-Fi, transport, accessibility, catering, and safety guidance.",
      fields: [
        "conferenceId",
        "category",
        "title",
        "answer",
        "keywords",
        "isPublished",
        "updatedAt",
      ],
      defaultFields: ["category", "title", "answer", "keywords"],
      searchableFields: ["category", "title", "answer", "keywords"],
    },
  },
  allowedFilters: [
    "day",
    "date",
    "keywords",
    "title",
    "theme",
    "venueHall",
    "type",
    "categoryName",
    "status",
    "isActive",
    "isPublished",
    "year",
    "conferenceYear",
    "mediaType",
    "reportType",
    "category",
    "isFeatured",
  ],
  allowedSortFields: [
    "day",
    "date",
    "startTime",
    "toTime",
    "endTime",
    "startMinutes",
    "sortOrder",
    "displayOrder",
    "title",
    "name",
    "year",
    "conferenceYear",
    "publicationDate",
  ],
};

function compactPlannerSchema() {
  const tables = Object.entries(REC_SCHEMA.tables)
    .map(([name, table]) => {
      return [
        `- ${name} (${table.label}): ${table.purpose}`,
        `  Fields: ${table.fields.join(", ")}`,
        `  Default fields: ${table.defaultFields.join(", ")}`,
      ].join("\n");
    })
    .join("\n");

  return [
    `Schema version: ${REC_SCHEMA_VERSION}`,
    `Active conference: ${REC_SCHEMA.activeConference.title} (${REC_SCHEMA.activeConference.shortName})`,
    `Default scope rule: ${REC_SCHEMA.activeConference.defaultFilter}`,
    `Historical scope rule: ${REC_SCHEMA.activeConference.historicalRule}`,
    "Planner-allowed tables and fields:",
    tables,
    `Allowed filters: ${REC_SCHEMA.allowedFilters.join(", ")}`,
    `Allowed sort fields: ${REC_SCHEMA.allowedSortFields.join(", ")}`,
    "Do not request private registration, coupon, lock, verification, or attendee tables.",
  ].join("\n");
}

export function getPlannerSchemaMarkdown() {
  const fullPath = path.join(process.cwd(), REC_SCHEMA_MARKDOWN_PATH);

  try {
    return fs.readFileSync(fullPath, "utf8");
  } catch {
    return compactPlannerSchema();
  }
}

export function getPlannerSchemaPrompt() {
  return [
    `Schema version: ${REC_SCHEMA_VERSION}`,
    "Scope: public REC conference data. Default to the active REC26 & EXPO conference unless the user explicitly asks for a year, REC edition, or previous/past/history data.",
    "Never request registrations, coupons, locks, verifications, attendees, users, or private tables.",
    "Tables:",
    "- conferences: dates, venue, location, theme, registration status, fees, limits, contact, website.",
    "- programs: programme title, description, day count, venue halls, status.",
    "- timeBlocks: day/date/time blocks, breaks, lunch, exhibition blocks, labels, halls, notes.",
    "- sessions: session title, day, start/end time, venue hall, theme, preamble/details, organizer, speakers, status.",
    "- sponsorCategories: sponsor/partner category name, description, display order, active flag.",
    "- sponsors: sponsor/partner name, category, description, website, featured/active flags.",
    "- mediaItems: published photo albums, videos, external links, thumbnails, and sample image links by conference edition.",
    "- reports: published conference reports, proceedings, outcomes, communiques, summaries, PDF links, and cover images by conference edition.",
    "- operationalInfo: published active-conference venue and visitor guidance maintained by admins.",
    "Allowed filters: day, date, keywords, title, theme, venueHall, type, categoryName, category, status, isActive, isPublished, isFeatured, year, conferenceYear, mediaType, reportType.",
    "Allowed sort fields: day, date, startTime, toTime, endTime, startMinutes, sortOrder, displayOrder, title, name, year, conferenceYear, publicationDate.",
    "Good table choices: session/topic/recommendation questions -> sessions; schedule/block/break/lunch questions -> timeBlocks; sponsor/partner questions -> sponsors plus sponsorCategories; photo/video/gallery questions -> mediaItems; report/proceedings/outcomes/communique questions -> reports; guest logistics such as Wi-Fi, transport, accessibility, catering, or safety -> operationalInfo; overview/date/venue/theme/register/cost/contact -> conferences.",
    "When historical scope is explicit, include the requested year or conferenceYear filter in every operation that supports it.",
  ].join("\n");
}
