services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: conference_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage